In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('/Users/slanka/workspace/delete/didactic-tribble/dfs/people_big.csv')

In [5]:
df.head(5)

   id     name  age gender state  income signup_date  referrer_id
0   1   Joshua   56      F    TX   52289  2020-07-03       7993.0
1   2  Mallory   46      F    CA   71716  2023-10-22       1460.0
2   3  Antonio   32      F    TX  130545  2024-10-07       6967.0
3   4   Melvin   60      M    CA   59342  2025-01-02       7035.0
4   5     Chad   25      M    IL  134597  2023-11-29       9048.0

In [21]:
df.groupby('state').sum('income').sort_values(by="income", ascending=False)

              id     age      income  referrer_id
state
NY     841524345  687526  1522769637   84299783.0
WA     834168509  687135  1511842607   83416826.0
FL     842038648  684081  1500581594   84249112.0
IL     833388155  684089  1500155196   83765486.0
TX     829440797  682968  1494755955   82436229.0
CA     819489546  676449  1491096915   82720607.0

In [26]:
df.groupby(['gender', 'state']).mean('income')

                        id        age        income  referrer_id
gender state
F      CA     50020.533398  40.892499  90546.011112  4970.640329
       FL     50399.822246  41.009572  89704.053677  5039.015511
       IL     49796.710945  41.063886  89662.641273  4978.642194
       NY     50143.045514  40.836104  90693.700153  5062.825943
       TX     50140.145719  40.921536  89984.969950  4971.249732
       WA     50319.418723  41.422128  90598.440851  5015.062371
M      CA     49279.060297  41.077073  90136.942499  5054.536470
       FL     50490.450883  40.956156  90088.166726  5055.949283
       IL     50110.246930  40.947061  90176.931442  5064.716637
       NY     49989.333013  40.974541  90500.344182  4967.817822
       TX     49631.739684  41.237864  89823.057888  4945.667476
       WA     49673.949888  40.945278  90612.271717  4984.389835

In [31]:
df.groupby('referrer_id').count().sort_values('id', ascending=False)

referrer_id
2242.0    23
7136.0    23
4194.0    23
3384.0    22
4716.0    22
          ..
9267.0     2
3264.0     1
6829.0     1
4511.0     1
1489.0     1
Name: id, Length: 9998, dtype: int64

In [44]:
df['signup_year'] = df.apply(lambda r: r['signup_date'].split('-')[0], axis=1)

df.groupby('signup_year')['id'].count()

In [55]:
cond = (lambda r: r['state']=='CA' and r['income']> 100000)
df[df.apply(cond, axis=1)]

,id,name,age,gender,state,income,signup_date,referrer_id,signup_year
16,17,Nathan,39,F,CA,148470,2021-08-03,3948.0,2021
26,27,Larry,39,M,CA,147327,2024-01-10,6120.0,2024
33,34,Jeremiah,32,M,CA,149125,2023-05-07,9083.0,2023
49,50,Connor,37,M,CA,136525,2021-07-06,7696.0,2021
58,59,David,34,F,CA,117169,2021-03-28,3465.0,2021
...,...,...,...,...,...,...,...,...,...
99970,99971,Patrick,56,M,CA,145255,2020-12-13,8244.0,2020
99976,99977,Wendy,40,M,CA,131368,2022-10-26,6667.0,2022
99980,99981,Austin,29,F,CA,141691,2024-10-30,8742.0,2024
99983,99984,Joseph,44,M,CA,146303,2024-01-23,5038.0,2024
99994,99995,Dylan,21,M,CA,135022,2021-01-03,4651.0,2021

In [59]:
pd.merge(df, df, left_on='id', right_on='referrer_id', how='inner')['referrer_id_y']

0           1.0
1           1.0
2           1.0
3           1.0
4           1.0
          ...
99986    9999.0
99987    9999.0
99988    9999.0
99989    9999.0
99990    9999.0
Name: referrer_id_y, Length: 99991, dtype: float64

In [64]:
df.groupby("name")["id"].nunique()

name
Aaron      326
Abigail    114
Adam       348
Adrian      73
Adriana     34
          ...
Yolanda     70
Yvette      21
Yvonne      49
Zachary    298
Zoe          8
Name: id, Length: 690, dtype: int64

In [77]:
100*(df['referrer_id'].isnull().count()/df['referrer_id'].notna().count())

np.float64(100.0)